nombre: Crear APK


en:

  empujar:

    sucursales:

      - principal


empleos:

  construir:

    runs-on: ubuntu-latest


    pasos:

      - nombre: Fuente de pago

        Usos: acciones/checkout@v4


      - nombre: Configurar JDK 17

        Usos: actions/setup-java@v4

        con:

          distribución: temurin

          versión de java: 17


      - nombre: Configurar el SDK de Android

        Usos: android-actions/setup-android@v3


      - nombre: Configurar Gradle

        Usos: gradle/actions/setup-gradle@v4


      - nombre: Build Debug APK

        ejecutar: gradle assembleDebug --stacktrace


      - nombre: Subir APK

        Usos: acciones/cargar-artefacto@v4

        con:

          nombre: app-debug-apk

          Ruta: app/build/outputs/apk/debug/app-debug.apk
      - nombre: Configurar el SDK de Android

        Usos: android-actions/setup-android@v3


      - nombre: Configurar Gradle

        Usos: gradle/actions/setup-gradle@v4


      - nombre: Build Debug APK

        ejecutar: gradle assembleDebug --stacktrace


      - nombre: Subir APK

        Usos: acciones/cargar-artefacto@v4

        con:

          nombre: app-debug-apk

          Ruta: app/build/outputs/apk/debug/app-debug.apk
